pipeline 
{
    agent any   
    stages 
    {  
        stage('Build') 
        {
            steps 
            {
                echo 'dotnet biuld -c Release' 
            }
        }
    

        stage('Test') 
        {
            steps 
            {
                echo 'dotnet test --filter Name~"SwitchLanguage"' 
            }
        }
        
    }
}