pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo 'dotnet test --filter Name~"SwitchLanguage"'
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
    }
}

