pipeline {
    agent any      
    
    stages { 

            stage('Encoding') {
            steps
            {
               echo 'chcp 65001'
            }

            }
    
            stage('Test') {
            steps 
            {
                 echo 'dotnet test --filter Name~"SwitchLanguage"'
            }
        }
        
    }
}